version: "3"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "desafio2-docker-db"
      MYSQL_ROOT_PASSWORD: "root123"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s
    networks:
      - nodenet

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    environment:
      DB_HOST: "db"
      DB_USER: "root"
      DB_PASS: "root123"
      DB_DATABASE: "desafio2-docker-db"
    volumes:
      - ./node:/app
    networks:
      - nodenet
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  nodenet:
    driver: bridge
